//time zone constant.
var time_zone = [
    {"value":"-12","display":"(GMT -12:00) Eniwetok, Kwajalein"},
    {"value":"-11","display":"(GMT -11:00) Midway Island, Samoa"},
    {"value":"-10","display":"(GMT -10:00) Hawaii"},
    {"value":"-9","display":"(GMT -09:00) Alaska"},
    {"value":"-8","display":"(GMT -08:00) Pacific Time (US & Canada), Tijuana"},
    {"value":"-7","display":"(GMT -07:00) Mountain Time (US & Canada), Arizona"},
    {"value":"-6","display":"(GMT -06:00) Central Time (US & Canada), Mexico City"},
    {"value":"-5","display":"(GMT -05:00) Eastern Time (US & Canada), Bogota, Lima, Quito"},
    {"value":"-4","display":"(GMT -04:00) Atlantic Time (Canada), Caracas, La Paz"},
    {"value":"-3.5","display":"(GMT -03:30) Newfoundland"},
    {"value":"-3","display":"(GMT -03:00) Brassila, Buenos Aires, Georgetown, Falkland Is"},
    {"value":"-2","display":"(GMT -02:00) Mid-Atlantic, Ascension Is., St. Helena"},
    {"value":"-1","display":"(GMT -01:00) Azores, Cape Verde Islands"},
    {"value":"0","display":"(GMT) Casablanca, Dublin, Edinburgh, London, Lisbon, Monrovia"},
    {"value":"1","display":"(GMT +01:00) Amsterdam, Berlin, Brussels, Madrid, Paris, Rome"},
    {"value":"2","display":"(GMT +02:00) Cairo, Helsinki, Kaliningrad, South Africa"},
    {"value":"3","display":"(GMT +03:00) Baghdad, Riyadh, Moscow, Nairobi"},
    {"value":"3.5","display":"(GMT +03:30) Tehran"},
    {"value":"4","display":"(GMT +04:00) Abu Dhabi, Baku, Muscat, Tbilisi"},
    {"value":"4.5","display":"(GMT +04:30) Kabul"},
    {"value":"5","display":"(GMT +05:00) Ekaterinburg, Islamabad, Karachi, Tashkent"},
    {"value":"5.5","display":"(GMT +05:30) Bombay, Calcutta, Madras, New Delhi"},
    {"value":"5.75","display":"(GMT +05:45) Katmandu"},
    {"value":"6","display":"(GMT +06:00) Almaty, Colombo, Dhaka, Novosibirsk"},
    {"value":"6.5","display":"(GMT +06:30) Rangoon"},
    {"value":"7","display":"(GMT +07:00) Bangkok, Hanoi, Jakarta"},
    {"value":"8","display":"(GMT +08:00) Beijing, Hong Kong, Perth, Singapore, Taipei"},
    {"value":"9","display":"(GMT +09:00) Osaka, Sapporo, Seoul, Tokyo, Yakutsk"},
    {"value":"9.5","display":"(GMT +09:30) Adelaide, Darwin"},
    {"value":"10","display":"(GMT +10:00) Canberra, Guam, Melbourne, Sydney, Vladivostok"},
    {"value":"11","display":"(GMT +11:00) Magadan, New Caledonia, Solomon Islands"},
    {"value":"12","display":"(GMT +12:00) Auckland, Wellington, Fiji, Marshall Island"}
];

//country constant.
var countrys = [
    {"value":"US","display":"United States"},
    {"value":"AF","display":"Afghanistan"},
    {"value":"AL","display":"Albania"},
    {"value":"DZ","display":"Algeria"},
    {"value":"AS","display":"American Samoa"},
    {"value":"AD","display":"Andorra"},
    {"value":"AO","display":"Angola"},
    {"value":"AI","display":"Anguilla"},
    {"value":"AQ","display":"Antarctica"},
    {"value":"AG","display":"Antigua and Barbuda"},
    {"value":"AR","display":"Argentina"},
    {"value":"AM","display":"Armenia"},
    {"value":"AW","display":"Aruba"},
    {"value":"AU","display":"Australia"},
    {"value":"AT","display":"Austria"},
    {"value":"AZ","display":"Azerbaijan"},
    {"value":"BS","display":"Bahamas"},
    {"value":"BH","display":"Bahrain"},
    {"value":"BD","display":"Bangladesh"},
    {"value":"BB","display":"Barbados"},
    {"value":"BY","display":"Belarus"},
    {"value":"BE","display":"Belgium"},
    {"value":"BZ","display":"Belize"},
    {"value":"BJ","display":"Benin"},
    {"value":"BM","display":"Bermuda"},
    {"value":"BT","display":"Bhutan"},
    {"value":"BO","display":"Bolivia"},
    {"value":"BA","display":"Bosnia and Herzegowina"},
    {"value":"BW","display":"Botswana"},
    {"value":"BV","display":"Bouvet Island"},
    {"value":"BR","display":"Brazil"},
    {"value":"VG","display":"Virgin Islands (British)"},
    {"value":"IO","display":"British Indian Ocean Territory"},
    {"value":"BN","display":"Brunei Darussalam"},
    {"value":"BG","display":"Bulgaria"},
    {"value":"BF","display":"Burkina Faso"},
    {"value":"BI","display":"Burundi"},
    {"value":"KH","display":"Cambodia"},
    {"value":"CM","display":"Cameroon"},
    {"value":"CA","display":"Canada"},
    {"value":"CV","display":"Cape Verde"},
    {"value":"KY","display":"Cayman Islands"},
    {"value":"CF","display":"Central African Republic"},
    {"value":"TD","display":"Chad"},
    {"value":"CL","display":"Chile"},
    {"value":"CN","display":"China"},
    {"value":"CX","display":"Christmas Island"},
    {"value":"CC","display":"Cocos (Keeling) Islands"},
    {"value":"CO","display":"Colombia"},
    {"value":"KM","display":"Comoros"},
    {"value":"CG","display":"Congo"},
    {"value":"CD","display":"Congo, Democratic Republic"},
    {"value":"CK","display":"Cook Islands"},
    {"value":"CR","display":"Costa Rica"},
    {"value":"CI","display":"Cote D'Ivoire"},
    {"value":"HR","display":"Croatia"},
    {"value":"CY","display":"Cyprus"},
    {"value":"CZ","display":"Czech Republic"},
    {"value":"DK","display":"Denmark"},
    {"value":"DJ","display":"Djibouti"},
    {"value":"DM","display":"Dominica"},
    {"value":"DO","display":"Dominican Republic"},
    {"value":"TP","display":"East Timor"},
    {"value":"EC","display":"Ecuador"},
    {"value":"EG","display":"Egypt"},
    {"value":"SV","display":"El Salvador"},
    {"value":"GQ","display":"Equatorial Guinea"},
    {"value":"ER","display":"Eritrea"},
    {"value":"EE","display":"Estonia"},
    {"value":"ET","display":"Ethiopia"},
    {"value":"FK","display":"Falkland Islands (Malvinas)"},
    {"value":"FO","display":"Faroe Islands"},
    {"value":"FJ","display":"Fiji"},
    {"value":"FI","display":"Finland"},
    {"value":"FR","display":"France"},
    {"value":"GF","display":"French Guiana"},
    {"value":"PF","display":"French Polynesia"},
    {"value":"TF","display":"French Southern Territories"},
    {"value":"GA","display":"Gabon"},
    {"value":"GM","display":"Gambia"},
    {"value":"GE","display":"Georgia"},
    {"value":"DE","display":"Germany"},
    {"value":"GH","display":"Ghana"},
    {"value":"GI","display":"Gibraltar"},
    {"value":"GR","display":"Greece"},
    {"value":"GL","display":"Greenland"},
    {"value":"GD","display":"Grenada"},
    {"value":"GP","display":"Guadeloupe"},
    {"value":"GU","display":"Guam"},
    {"value":"GT","display":"Guatemala"},
    {"value":"GN","display":"Guinea"},
    {"value":"GW","display":"Guinea-Bissau"},
    {"value":"GY","display":"Guyana"},
    {"value":"HT","display":"Haiti"},
    {"value":"HM","display":"Heard and McDonald Islands"},
    {"value":"HN","display":"Honduras"},
    {"value":"HK","display":"Hong Kong"},
    {"value":"HU","display":"Hungary"},
    {"value":"IS","display":"Iceland"},
    {"value":"IN","display":"India"},
    {"value":"ID","display":"Indonesia"},
    {"value":"IE","display":"Ireland"},
    {"value":"IL","display":"Israel"},
    {"value":"IT","display":"Italy"},
    {"value":"JM","display":"Jamaica"},
    {"value":"JP","display":"Japan"},
    {"value":"JO","display":"Jordan"},
    {"value":"KZ","display":"Kazakhstan"},
    {"value":"KE","display":"Kenya"},
    {"value":"KI","display":"Kiribati"},
    {"value":"KR","display":"Korea - Republic of"},
    {"value":"KW","display":"Kuwait"},
    {"value":"KG","display":"Kyrgyzstan"},
    {"value":"LA","display":"Lao People's Democratic Republic"},
    {"value":"LV","display":"Latvia"},
    {"value":"LB","display":"Lebanon"},
    {"value":"LS","display":"Lesotho"},
    {"value":"LR","display":"Liberia"},
    {"value":"LI","display":"Liechtenstein"},
    {"value":"LT","display":"Lithuania"},
    {"value":"LU","display":"Luxembourg"},
    {"value":"MO","display":"Macau"},
    {"value":"MK","display":"Macedonia (former Yugoslav Rep.)"},
    {"value":"MG","display":"Madagascar"},
    {"value":"MW","display":"Malawi"},
    {"value":"MY","display":"Malaysia"},
    {"value":"MV","display":"Maldives"},
    {"value":"ML","display":"Mali"},
    {"value":"MT","display":"Malta"},
    {"value":"MH","display":"Marshall Islands"},
    {"value":"MQ","display":"Martinique"},
    {"value":"MR","display":"Mauritania"},
    {"value":"MU","display":"Mauritius"},
    {"value":"YT","display":"Mayotte"},
    {"value":"MX","display":"Mexico"},
    {"value":"FM","display":"Micronesia - Federated States of"},
    {"value":"MD","display":"Moldova - Republic of"},
    {"value":"MC","display":"Monaco"},
    {"value":"MN","display":"Mongolia"},
    {"value":"MS","display":"Montserrat"},
    {"value":"MA","display":"Morocco"},
    {"value":"MZ","display":"Mozambique"},
    {"value":"MM","display":"Myanmar"},
    {"value":"NA","display":"Namibia"},
    {"value":"NR","display":"Nauru"},
    {"value":"NP","display":"Nepal"},
    {"value":"NL","display":"Netherlands"},
    {"value":"AN","display":"Netherlands Antilles"},
    {"value":"NC","display":"New Caledonia"},
    {"value":"NZ","display":"New Zealand"},
    {"value":"NI","display":"Nicaragua"},
    {"value":"NE","display":"Niger"},
    {"value":"NG","display":"Nigeria"},
    {"value":"NU","display":"Niue"},
    {"value":"NF","display":"Norfolk Island"},
    {"value":"MP","display":"Northern Mariana Islands"},
    {"value":"NO","display":"Norway"},
    {"value":"OM","display":"Oman"},
    {"value":"PK","display":"Pakistan"},
    {"value":"PW","display":"Palau"},
    {"value":"PS","display":"Palestine"},
    {"value":"PA","display":"Panama"},
    {"value":"PG","display":"Papua New Guinea"},
    {"value":"PY","display":"Paraguay"},
    {"value":"PE","display":"Peru"},
    {"value":"PH","display":"Philippines"},
    {"value":"PN","display":"Pitcairn"},
    {"value":"PL","display":"Poland"},
    {"value":"PT","display":"Portugal"},
    {"value":"PR","display":"Puerto Rico"},
    {"value":"QA","display":"Qatar"},
    {"value":"RE","display":"Reunion"},
    {"value":"RO","display":"Romania"},
    {"value":"RU","display":"Russian Federation"},
    {"value":"RW","display":"Rwanda"},
    {"value":"KN","display":"Saint Kitts and Nevis"},
    {"value":"LC","display":"Saint Lucia"},
    {"value":"VC","display":"Saint Vincent and the Grenadines"},
    {"value":"WS","display":"Samoa"},
    {"value":"SM","display":"San Marino"},
    {"value":"ST","display":"Sao Tome and Principe"},
    {"value":"SA","display":"Saudi Arabia"},
    {"value":"SN","display":"Senegal"},
    {"value":"CS","display":"Serbia and Montenegro"},
    {"value":"SC","display":"Seychelles"},
    {"value":"SL","display":"Sierra Leone"},
    {"value":"SG","display":"Singapore"},
    {"value":"SK","display":"Slovakia (Slovak Republic)"},
    {"value":"SI","display":"Slovenia"},
    {"value":"SB","display":"Solomon Islands"},
    {"value":"SO","display":"Somalia"},
    {"value":"ZA","display":"South Africa"},
    {"value":"ES","display":"Spain"},
    {"value":"LK","display":"Sri Lanka"},
    {"value":"SH","display":"St. Helena"},
    {"value":"PM","display":"St. Pierre and Miquelon"},
    {"value":"SR","display":"Suriname"},
    {"value":"SJ","display":"Svalbard and Jan Mayen Islands"},
    {"value":"SZ","display":"Swaziland"},
    {"value":"SE","display":"Sweden"},
    {"value":"CH","display":"Switzerland"},
    {"value":"TW","display":"Taiwan"},
    {"value":"TJ","display":"Tajikistan"},
    {"value":"TZ","display":"Tanzania - United Republic of"},
    {"value":"TH","display":"Thailand"},
    {"value":"TG","display":"Togo"},
    {"value":"TK","display":"Tokelau"},
    {"value":"TO","display":"Tonga"},
    {"value":"TT","display":"Trinidad and Tobago"},
    {"value":"TN","display":"Tunisia"},
    {"value":"TR","display":"Turkey"},
    {"value":"TM","display":"Turkmenistan"},
    {"value":"TC","display":"Turks and Caicos Islands"},
    {"value":"TV","display":"Tuvalu"},
    {"value":"UG","display":"Uganda"},
    {"value":"UA","display":"Ukraine"},
    {"value":"AE","display":"United Arab Emirates"},
    {"value":"GB","display":"United Kingdom"},
    {"value":"UM","display":"United States Minor Outlying Islands"},
    {"value":"UY","display":"Uruguay"},
    {"value":"UZ","display":"Uzbekistan"},
    {"value":"VU","display":"Vanuatu"},
    {"value":"VA","display":"Vatican City State (Holy See)"},
    {"value":"VE","display":"Venezuela"},
    {"value":"VN","display":"Vietnam"},
    {"value":"VI","display":"Virgin Islands (U.S.)"},
    {"value":"WF","display":"Wallis And Futuna Islands"},
    {"value":"EH","display":"Western Sahara"},
    {"value":"YE","display":"Yemen"},
    {"value":"YU","display":"Yugoslavia"},
    {"value":"ZM","display":"Zambia"},
    {"value":"ZW","display":"Zimbabwe"}
];


var month_list = [
    {"value":"","display":"Month"},
    {"value":"1","display":"January"},
    {"value":"2","display":"February"},
    {"value":"3","display":"March"},
    {"value":"4","display":"April"},
    {"value":"5","display":"May"},
    {"value":"6","display":"June"},
    {"value":"7","display":"July"},
    {"value":"8","display":"August"},
    {"value":"9","display":"September"},
    {"value":"10","display":"October"},
    {"value":"11","display":"November"},
    {"value":"12","display":"December"}
];